config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :children
  resources :reports

  root 'home#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    @children = Child.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new(:room_id => params[:room_id])
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to proc { room_url(@child.room_id) }, notice: 'Child was successfully created.' }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to proc { room_url(@child.room_id) }, notice: 'Child was successfully updated.' }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to proc { room_url(@child.room_id) }, notice: 'Child was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:first_name, :last_name, :room_id)
    end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<div class="col-xs-12 col-sm-9 col-md-9 col-lg-6 col-xl-4 mx-auto">
	<%= simple_form_for(@child) do |f| %>
	<%= f.error_notification %>
	  <div class="form-group">
	    <%= f.input :first_name, required: true, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	  </div>
	<div class="form-group">
		<%= f.input :last_name, required: true, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	  <%= f.hidden_field :room_id %>

		<!--<div class="form-group">-->
		<!--  <label for="inputState">Room</label>-->
	 <!--   <%#= f.collection_select(:room_id, Room.all.sort_by(&:custom_room_sort), :id, :title, {prompt: "Choose room", required: true}, {class: "form-control"}) %>-->
		<!--</div>-->
	  <%= f.button :submit, class:"btn btn-primary btn-block mt-3" %>
	<% end %>
</div>

app/views/children/edit.html.erb
<div class="bg">
	<h1 class="text-center header-bg py-5 mb-5">Editing Child</h1>
    <div class="col-xs-12 col-sm-9 col-md-9 col-lg-6 col-xl-4 mx-auto">
    	<%= simple_form_for(@child) do |f| %>
    	<%= f.error_notification %>
    	  <div class="form-group">
    	    <%= f.input :first_name, required: true, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
    	  </div>
    	<div class="form-group">
    		<%= f.input :last_name, required: true, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
    	</div>
    		<div class="form-group">
    		  <label for="inputState">Room</label>
    	    <%= f.collection_select(:room_id, Room.all.sort_by(&:custom_room_sort), :id, :title, {:selected => @child.room_id}, {class: "form-control"}) %>
    		</div>
    	  <%= f.button :submit, "Update", class:"btn btn-primary btn-block mt-3" %>
    	<% end %>
    </div>
</div>

app/views/children/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Children</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.first_name %></td>
        <td><%= child.last_name %></td>
        <td><%= child.room.title %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<div class="bg">
    <h1 class="text-center header-bg py-5 mb-5">New Child</h1>
    
    <%= render 'form', child: @child %>
</div>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @child.first_name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @child.last_name %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>