config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :children
  resources :reports

  root 'home#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :children, dependent: :destroy

    mount_uploader :room_image, RoomImageUploader
    
    validates :title, :room_image, presence: true
    
    resourcify
    
    def custom_room_sort
        title.scan(/\d/).join('').to_i
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :update, :destroy]


  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @children = Child.where('room_id = ?', @room.id)
    @children = @children.sort_by{ |c| c.last_name }
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to root_url, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to root_url, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :room_image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="col-xs-12 col-sm-9 col-md-9 col-lg-6 col-xl-4 mx-auto">
  <%= simple_form_for @room, html: { multipart: true }  do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.input :room_image, label: "Pick an image", input_html: { class: "form-control-file", type: "file" }, wrapper: false, label_html: { class: "form-control-file" } %>
  </div>
  <div class="form-group">
    <%= f.input :title, label: "Title", input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
  </div>
  <%= f.button :submit, class:"button btn-primary btn-block" %>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<div class="bg">
    <h1 class="text-center header-bg py-5 mb-5">Editing Room</h1>

    <%= render 'form', room: @room %>
</div>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= image_tag(room.room_image_url) %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<div class="bg">
    <h1 class="text-center header-bg py-5 mb-5">New Room</h1>

    <%= render 'form', room: @room %>
</div>

app/views/rooms/show.html.erb
<h1 class="text-center header-bg py-5"><%= @room.title %></h1>
<div class="text-center">
<% if has_role?(:admin) || has_role?(:teacher) %>
  <%= link_to 'New Child', new_child_path(:room_id => @room.id), :class => "btn btn-primary" %>
<% end %>
</div>
<div class="row">
<% @children.each do |child| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 my-2">
    <div class="card">
      <div class="card-header card-header-bg">
        <%= child.full_name %>
      </div>
      <div class="card-body bg-light">
        <h5 class="card-title"></h5>
          <% if has_role?(:admin) || has_role?(:teacher) %>
            <%= link_to 'Edit Child', edit_child_path(child), :class => "btn btn-outline-primary btn-sm mt-1" %>
            <%= link_to 'Destroy', child, :class => "btn btn-outline-danger btn-sm mt-1", method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to 'Add Daily Report', new_report_path(:child_id => child.id), :class => "btn btn-outline-primary btn-sm mt-1" %>
            <%= link_to 'Daily Reports', reports_url(:child_id => child.id), :class => "btn btn-outline-primary btn-sm mt-1" %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>