config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :children
  resources :reports

  root 'home#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/report.rb
class Report < ApplicationRecord
    
    belongs_to :child
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.where(:child_id => params[:child_id]).order('created_at DESC')
    # @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new(:child_id => params[:child_id])
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @child = Child.find_by(:id => @report.child_id)

    respond_to do |format|
      if @report.save
        format.html { redirect_to proc { room_url(@child.room_id) }, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    @child = Child.find_by(:id => @report.child_id)
    
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to proc { room_url(@child.room_id) }, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:meals, :naps, :bathroom, :activities, :summary, :child_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div class="col-xs-12 col-sm-9 col-md-9 col-lg-6 col-xl-4 mx-auto">
  <%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
	  <%= f.input :meals, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :naps, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :bathroom, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :activities, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :summary, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
  <div class="form-group">
	<%= f.hidden_field :child_id %>
  <%= f.button :submit, "Create Daily Report", class:"btn btn-primary btn-block mt-3" %>
<% end %>
</div>

app/views/reports/edit.html.erb
<div class="bg">
    <h1 class="text-center header-bg py-5 mb-5">Editing Daily Report</h1>
    <div class="col-xs-12 col-sm-9 col-md-9 col-lg-6 col-xl-4 mx-auto">
  <%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
	  <%= f.input :meals, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :naps, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :bathroom, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :activities, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
	<div class="form-group">
	  <%= f.input :summary, required: false, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
	</div>
  <div class="form-group">
  <%= f.button :submit, "Update", class:"btn btn-primary btn-block mt-3" %>
<% end %>
</div>
</div>

app/views/reports/index.html.erb
<h1 class="text-center header-bg py-5">Daily Reports</h1>
<div class="row">
  <% @reports.each do |report| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 my-2">
      <div class="card">
        <div class="card-header card-header-bg">
          <%= report.created_at %>
        </div>
        <div class="card-body bg-light">
          <h5 class="card-title">Meals</h5>
          <p class="card-text"><%= report.meals %></p>
          <h5 class="card-title">Naps</h5>
          <p class="card-text"><%= report.naps %></p>
          <h5 class="card-title">Bathroom</h5>
          <p class="card-text"><%= report.bathroom %></p>
          <h5 class="card-title">Activities</h5>
          <p class="card-text"><%= report.activities %></p>
          <h5 class="card-title">Summary</h5>
          <p class="card-text"><%= report.summary %></p>
          <%= link_to 'Edit Report', edit_report_path(report), :class => "btn btn-outline-primary btn-sm mt-1" %>
          <%= link_to 'Destroy', report, :class => "btn btn-outline-danger btn-sm mt-1", method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reports/new.html.erb
<div class="bg">
    <h1 class="text-center header-bg py-5 mb-5">New Daily Report</h1>

    <%= render 'form', room: @report %>
</div>

app/views/reports/show.html.erb
<p>
  <strong>Meals:</strong>
  <%= @report.meals %>
</p>

<p>
  <strong>Naps:</strong>
  <%= @report.naps %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @report.bathroom %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @report.activities %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @report.summary %>
</p>

<p>
  <strong>Child:</strong>
  <%= @report.child_id %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>